name: ğŸ”„ åŒæ­¥ Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    name: ğŸ”„ åŒæ­¥ ğŸ”„
    if: ${{ github.actor == 'sam01101' }}
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€
        run: |
          tokens=(${{ secrets.ALT_PA_TOKENS }})
          for ((i=0; i < ${#tokens[@]}; i++)); do
              alt_num=$(($i+1))
              echo "Syncing repo for esj-${alt_num}..."
              curl -s --location --request POST "https://api.github.com/repos/esj-${alt_num}/esjzone-mirror/merge-upstream" \
          --header 'Accept: application/vnd.github.v3+json' \
          --header "Authorization: token ${tokens[$i]}" \
          --header 'Content-Type: application/json' \
          --data-raw '{"branch": "master"}'
              echo "Done!"
          done