name: æ¸¬è©¦

on:
  workflow_dispatch:

jobs:
  debug:
    name: èª¿è©¦
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“£ Call ðŸ“£
        run: |
          tokens=(${{ secrets.ALT_PA_TOKENS }})
          total_workers=$((${#tokens[@]}*20))
          for ((i=0; i < ${#tokens[@]}; i++)); do
            alt_num=$(($i+1))
            worker_cfg=""
            start_index=$((20*$i-1))
            end_index=$((20*$alt_num))
            if [[ $start_index -lt 0 ]]; then start_index=0; fi
            for ((num=start_index; num < end_index; num++)); do
              worker_cfg+="{\"total_workers\":${total_workers},\"worker_numbers\":${num}}"
              if [[ num -ne $((end_index-1)) ]]; then
                worker_cfg+=","
              fi
            done
            end_index=$(($end_index-1))  # Display

            echo "Sending render request ${start_index}-${end_index} to esj-$alt_num"
            echo "{\"event_type\": \"call-render\", \"client_payload\": {\"include\":[${worker_cfg}]}}"
            curl -s --location --request POST "https://api.github.com/repos/esj-${alt_num}/esjzone-mirror/dispatches" \
              --header 'Accept: application/vnd.github.v3+json' \
              --header "Authorization: token ${tokens[$i]}" \
              --header 'Content-Type: application/json' \
              --data-raw "{\"event_type\": \"call-render\", \"client_payload\": {\"include\":[${worker_cfg}]}}"
            echo "OK"
          done