name: æ¸¬è©¦

on:
  workflow_dispatch:

jobs:
  merge-branches:
    name: åˆå¹¶Repo
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo branch ğŸ“¥
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ref: actions-compile
          token: ${{ secrets.PA_TOKEN }}

      - name: Setup
        run: |
          git fetch origin actions-client --depth=1
          git fetch origin actions-server --depth=1
          git checkout actions-compile
          git merge origin/actions-client origin/actions-server
#          for i in {0..39}; do git push origin :actions-compile-$i || true; done
